---
# Localhost only
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    user: {
      name: zsoltk,
      group: staff
    }
    go: {
      path: "/Users/{{ user.name }}/work/go"
    }

  roles:
    - { role: shell, tags: [ 'shell' ] }
    - { role: golang, tags: [ 'golang' ] }